services:
  - type: web
    name: habit-tracker-api
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habit-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
  - type: web
    name: habit-tracker-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
  
databases:
  - name: habit-tracker-db
    databaseName: habit_tracker
    user: habit_tracker_user